spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        inboundOrgChanges:
          binder: kafka
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: 
          - localhost:2181
          brokers: 
          - localhost:9092
  main:
    allow-bean-definition-overriding: true

#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoint:
    health:      
      enabled: true
    env:
      enabled: true
    refresh:
      enabled: true
    beans:
      enabled: true
  endpoints:
    web:      
      exposure:        
        include:        
        - info
        - env
        - refresh
        - beans
        - loggers